### ISSUE TITLE
合服问题

### ISSUE THREAD

**Issue by hstcscolor** [dwing4g/jane#1]
有考虑合服问题吗。准备仔细研究fane。还有看见文档两年多没更新了。有想补充的吗。想知道你的邮箱，方便交流。看了代码受益匪浅，谢谢！！

**Comment by dwing4g** [comment]
合服可以写个工具, 直接使用Storage接口, 同时读取多个数据库, 处理数据后写入一个数据库.

**Comment by dwing4g** [comment]
最近略更新了下源码及文档, 没有重要的改动. 没有特殊需求建议只看master分支.
