### ISSUE TITLE
genbeans.lua ,line 402

### ISSUE THREAD

**Issue by ssochi** [dwing4g/jane#2]

**Comment by ssochi** [comment]
name_u = function(var) return var.name:sub(1, 1):upper() .. var.name:sub(2) end,
在一些特殊情况下，比如 long sRid ;
sRid的getter应该是getsRid而不是getSRid;
这个问题导致jane与jackson等开源框架不兼容.

**Comment by dwing4g** [comment]
感谢反馈, 已修正.
