### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by nilslar** [dwing4g/jane#3]
Hi, How can I install it on debian linux?

**Comment by dwing4g** [comment]
> Hi, How can I install it on debian linux?

@nilslar 
Jane is based on Java that is compatible with almost all popular versions of Windows & MacOS & Linux.
The only native library for LevelDB is included for x64 on Windows & MacOS & Linux. You can also build this native library by yourself for other platform.
You can build Jane by Apache Ant. Use the build result (jane-core.jar & jane-native.jar & jars in lib) for your application. Or run start.bat / start.sh for example.
